### ISSUE TITLE
Terminal icon removal

### ISSUE THREAD

**Issue by seiflotfy** [deckarep/gosx-notifier#10]
Is there a way to not display an icon at all?

**Comment by deckarep** [comment]
Hmmm,

I'll look into it but I believe this might be a limitation of Apple's API. If you don't provide an icon, you'll see a generic terminal icon if I remember correctly.

-@deckarep

**Comment by deckarep** [comment]
Looks like it's not possible.  This implementation is based on the following XCode implementation: https://github.com/julienXX/terminal-notifier

See their readme in regards to the constraints around the icon.
